version: "3.8"
services:
  web:
    build: .
    image: registry.eu-de.bluemix.net/lvcz/ibm-cloud:0.0.0
    environment:
      MONGO_CONN: mongo
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
