version: "3.8"
services:
  web:
    build: .
    image: registry.eu-de.bluemix.net/lvcz/ibm-cloud:0.1.2
    environment:
      CONN_STRING: postgresql://scott:tiger@localhost/mydatabase
      MONGO_USERNAME: postgres
      MONGO_PASSWORD: postgres
    ports:
      - "5000:5000"
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080