apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: postgresqlcb-4c62-40
    helm.sh/chart: postgresql-9.8.11
    failure-domain.beta.kubernetes.io/region: fra
    failure-domain.beta.kubernetes.io/zone: "02"
spec:
  capacity:
    storage: "20Gi"
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "ibm/ibmc-block"
    options:
      "Lun": "0"
      "TargetPortal": "<IP_address>"
      "VolumeID": "183418456"
      "volumeName": "DSW02SEL2151698-1"