apiVersion: v1
kind: Secret
metadata:
  namespace: ibm-scrap
  name: ibm-secrets
type: Opaque
data:
  # AWS

  ASPNETCORE_ENVIRONMENT: UHJvZHVjdGlvbg==

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ibm-scrap
  name: ibm-conf
data:
  TZ: America/Sao_Paulo
  ASPNETCORE_ENVIRONMENT: Production
  

