apiVersion: v1
kind: Service
metadata:
  namespace: ibm-scrap
  name: ibm-service
  labels:
    app: ibm
spec:
  selector:
    app: ibm
  type: NodePort
  ports:
    - port: 5000
#      nodePort: 30237
